import type { FieldDef, FlightRecord } from './types'
import {
  BATN,
  BATN_CUSTOM,
  ELEMAG,
  FAILS,
  FLT1,
  FLT2,
  MODE,
  NAME_CUSTOM,
  NAMES,
  OBST,
  OK2,
  PLACE_CUSTOM,
  THIRD,
  WIND,
} from './masters'

/**
 * 入力方式はショートカット19のリスト／サブ処理に合わせる。
 */
export const FIELDS: FieldDef[] = [
  { no: 1, key: 'A_DRONE', label: '機種名と機体識別番号', group: 'pre', input: 'select', options: ['Mavic2Pro', 'Tello', 'Other'] },
  {
    no: 2,
    key: 'A_NAME1',
    label: '操縦者の氏名',
    group: 'pre',
    input: 'select',
    options: [...NAMES],
    allowCustom: true,
    customLabel: NAME_CUSTOM,
  },
  { no: 3, key: 'A_HELTH', label: '操縦者の体調', group: 'pre', input: 'choice2', options: [...OK2] },
  { no: 4, key: 'A_CARRY', label: '許可証、飛行日誌の携帯', group: 'pre', input: 'choice2', options: [...OK2] },
  {
    no: 5,
    key: 'A_NAME2',
    label: '安全運航管理者の氏名',
    group: 'pre',
    input: 'select',
    options: [...NAMES],
    allowCustom: true,
    customLabel: NAME_CUSTOM,
  },
  { no: 6, key: 'A_FLT1', label: '飛行目的', group: 'pre', input: 'select', options: [...FLT1] },
  { no: 7, key: 'A_FLT2', label: '飛行条件（複数可）', group: 'pre', input: 'select', options: [...FLT2], multi: true },
  { no: 8, key: 'A_OBST', label: '飛行空域の主な物理的障害物', group: 'pre', input: 'select', options: [...OBST] },
  { no: 9, key: 'A_ELEMAG', label: '飛行空域の主な電磁気障害物', group: 'pre', input: 'select', options: [...ELEMAG] },
  { no: 10, key: 'A_THIRD', label: '飛行空域の第３者', group: 'pre', input: 'select', options: [...THIRD] },
  { no: 11, key: 'A_WTH', label: '飛行空域の天候', group: 'ops', input: 'text' },
  { no: 12, key: 'A_RAIN%', label: '飛行空域の降水確率', group: 'ops', input: 'number' },
  { no: 13, key: 'A_WINDD', label: '飛行空域の地上風向', group: 'ops', input: 'select', options: [...WIND] },
  { no: 14, key: 'A_WINDS', label: '飛行空域の地上風速', group: 'ops', input: 'number' },
  { no: 15, key: 'A_TEMP', label: '飛行空域の地上気温', group: 'ops', input: 'number' },
  { no: 16, key: 'A_ATTA', label: '作動前:各機器の取り付け状態', group: 'ops', input: 'choice2', options: [...OK2] },
  { no: 17, key: 'A_PROP', label: '作動前:プロペラの損傷や歪み', group: 'ops', input: 'choice2', options: [...OK2] },
  { no: 18, key: 'A_FRAME', label: '作動前:フレームの傷や歪み', group: 'ops', input: 'choice2', options: [...OK2] },
  { no: 19, key: 'A_PERR', label: '作動前:操縦装置電源ONエラー', group: 'ops', input: 'choice2', options: [...OK2] },
  { no: 20, key: 'A_PBAT%', label: '作動前:操縦装置バッテリー量', group: 'ops', input: 'number' },
  { no: 21, key: 'A_ERR', label: '作動:機体電源ONエラー', group: 'ops', input: 'choice2', options: [...OK2] },
  {
    no: 22,
    key: 'A_BATN',
    label: '作動:機体バッテリー番号',
    group: 'ops',
    input: 'select',
    options: [...BATN],
    allowCustom: true,
    customLabel: BATN_CUSTOM,
  },
  { no: 23, key: 'A_BAT%', label: '作動:機体バッテリー量', group: 'ops', input: 'number' },
  { no: 24, key: 'A_BATB', label: '作動:機体バッテリーバランス', group: 'ops', input: 'choice2', options: [...OK2] },
  { no: 25, key: 'A_BATV', label: '作動:機体バッテリー電圧', group: 'ops', input: 'number' },
  { no: 26, key: 'A_BATT', label: '作動:機体バッテリー温度', group: 'ops', input: 'number' },
  { no: 27, key: 'A_REMID', label: '作動:リモートID動作', group: 'ops', input: 'choice2', options: [...OK2] },
  { no: 28, key: 'A_GNSS', label: '作動:GNSS捕捉数', group: 'ops', input: 'number' },
  { no: 29, key: 'A_MODE', label: '作動:操縦モード設定MODE', group: 'ops', input: 'select', options: [...MODE] },
  { no: 30, key: 'A_RTHH', label: '作動:RTH高度設定', group: 'ops', input: 'number' },
  { no: 31, key: 'A_MAXH', label: '作動:最大高度設定', group: 'ops', input: 'number' },
  { no: 32, key: 'A_MAXD', label: '作動:最大距離設定', group: 'ops', input: 'number' },
  { no: 33, key: 'A_FAILS', label: '作動:フェールセーフ設定', group: 'ops', input: 'select', options: [...FAILS] },
  { no: 34, key: 'A_LIGHT', label: '作動:機体灯火動作', group: 'ops', input: 'choice2', options: [...OK2] },
  { no: 35, key: 'A_CAM', label: '作動:機体カメラ画像', group: 'ops', input: 'choice2', options: [...OK2] },
  { no: 36, key: 'A_NOISE', label: '飛行:発動機やモーターの異音', group: 'ops', input: 'choice2', options: [...OK2] },
  { no: 37, key: 'A_STICK', label: '飛行:スティック、カメラ操作', group: 'ops', input: 'choice2', options: [...OK2] },
  { no: 38, key: 'A_DATE', label: '離陸日時', group: 'takeoff', input: 'datetime' },
  { no: 39, key: 'B_DATE', label: '着陸日時', group: 'takeoff', input: 'datetime' },
  { no: 40, key: null, label: '飛行時間', group: 'takeoff', input: 'flightDuration' },
  { no: 41, key: 'A_SR', label: '日の出時間', group: 'takeoff', input: 'time' },
  { no: 42, key: 'A_SS', label: '日の入時間', group: 'takeoff', input: 'time' },
  { no: 43, key: 'A_DATA2', label: '離陸地点の経度', group: 'takeoff', input: 'number' },
  { no: 44, key: 'A_DATA1', label: '離陸地点の緯度', group: 'takeoff', input: 'number' },
  { no: 45, key: 'A_DATA3', label: '離陸地点の高度', group: 'takeoff', input: 'number' },
  { no: 46, key: 'A_ADRS', label: '離陸地点の住所', group: 'takeoff', input: 'text' },
  {
    no: 47,
    key: 'A_POS',
    label: '離陸地点の場所',
    group: 'takeoff',
    input: 'select',
    options: [],
    allowCustom: true,
    customLabel: PLACE_CUSTOM,
  },
  { no: 48, key: 'B_DATA2', label: '着陸地点の経度', group: 'takeoff', input: 'number' },
  { no: 49, key: 'B_DATA1', label: '着陸地点の緯度', group: 'takeoff', input: 'number' },
  { no: 50, key: 'B_DATA3', label: '着陸地点の高度', group: 'takeoff', input: 'number' },
  { no: 51, key: 'B_ADRS', label: '着陸地点の住所', group: 'takeoff', input: 'text' },
  {
    no: 52,
    key: 'B_POS',
    label: '着陸地点の場所',
    group: 'takeoff',
    input: 'select',
    options: [],
    allowCustom: true,
    customLabel: PLACE_CUSTOM,
  },
  { no: 53, key: 'B_BAT%', label: '飛行後:機体バッテリー量', group: 'post', input: 'number' },
  { no: 54, key: 'B_BATB', label: '飛行後:機体バッテリーバランス', group: 'post', input: 'choice2', options: [...OK2] },
  { no: 55, key: 'B_BATV', label: '飛行後:機体バッテリー電圧', group: 'post', input: 'number' },
  { no: 56, key: 'B_BATT', label: '飛行後:機体バッテリー温度', group: 'post', input: 'number' },
  { no: 57, key: 'B_PBAT%', label: '飛行後:操縦装置バッテリー量', group: 'post', input: 'number' },
  { no: 58, key: 'B_ATTA', label: '飛行後:各機器の取り付け状態', group: 'post', input: 'choice2', options: [...OK2] },
  { no: 59, key: 'B_DIRT', label: '飛行後:機体ゴミ、汚れ等付着', group: 'post', input: 'choice2', options: [...OK2] },
  { no: 60, key: 'B_PROP', label: '飛行後:プロペラの損傷や歪み', group: 'post', input: 'choice2', options: [...OK2] },
  { no: 61, key: 'B_FRAME', label: '飛行後:フレームの傷や歪み', group: 'post', input: 'choice2', options: [...OK2] },
  { no: 62, key: 'B_FEVER', label: '飛行後:各機器からの異常な発熱', group: 'post', input: 'choice2', options: [...OK2] },
  { no: 63, key: 'REMARK', label: '飛行の安全に影響のあった事項', group: 'meta', input: 'text', skipEmptyCheck: true },
]

export const RECORD_KEYS = FIELDS.map((f) => f.key).filter((k): k is keyof FlightRecord => k != null)

export function emptyRecord(): FlightRecord {
  const r = {} as FlightRecord
  for (const k of RECORD_KEYS) r[k] = ''
  return r
}

export function filled(v: string | undefined | null): boolean {
  return String(v ?? '').trim() !== ''
}
